from funciones import *
f = f(raw_input("Enter your function : "))
print(f)
g = g(raw_input("Enter your g : "))
f1 = f1(f)
print(f1)
f2 = f2(f1)
f3 = evalfunct(f,3)
f4 = evalfunct(f1,3)
print(f2)
print(g)
print(f3)